# Generated by Django 5.1.6 on 2025-05-04 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posts', models.ManyToManyField(blank=True, related_name='in_reading_lists', to='blog.post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
