# Generated by Django 5.1.6 on 2025-05-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_comment_email_remove_comment_name'),
    ]

    operations = [
    ]
