# Generated by Django 5.1.6 on 2025-05-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_featured_image_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
