# Generated by Django 5.1.6 on 2025-07-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('👍', 'Like'), ('❤️', 'Love'), ('😲', 'Wow'), ('😄', 'Happy'), ('😢', 'Sad')], max_length=2),
        ),
    ]
